#!/bin/bash
#
# bootstrap installs things.
echo "Installing source hook on profile and rc..."
if [[ `grep dotfiles ~/.bashrc` == "" ]]; then
  echo "source ~/.dotfiles/load.sh" >> ~/.bashrc
  echo "source ~/.dotfiles/load.sh" >> ~/.bash_profile
  source ~/.dotfiles/load.sh
fi

## Run the install (I'd like to pull this out of rake, eventually)
#WHICH_RAKE=`which rake`
#if [ -n "$WHICH_RAKE" ] && [ ! -f ~/.dotfiles_installed ]; then
#  echo "Installing dotfiles..."
#  rake install && touch ~/.dotfiles_installed
#else
#  echo "Warning: No rake detected. Deferring installation."
#fi

